server:
  port: 80
  servlet:
    context-path: /shop
spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    # serverTimezone=GMT%2B8&
    username: root
    password: root

    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-wait: 10000
      min-idle: 3
      max-active: 20
      filters: stat,wall,logback
      use-global-data-source-stat: true
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    com.shop.dao: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  support-methods-arguments: true
  params: pageNum=currentPage,pageSize=pageSize
  helper-dialect: mysql

